
name: 'insert_by_period_integration_tests'
version: '1.0'

# require-dbt-version: inherit this from dbt-utils

config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'integration_tests'

dispatch:
 - macro_namespace: dbt_utils
   search_order: ['spark_utils', 'dbt_utils', 'insert_by_period_integration_tests']


model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
    - "dbt_packages"

seeds:
  +quote_columns: false