name: 'lambda_view_approaches'
version: '0.1.0'
config-version: 2

profile: 'jaffle_shop'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  lambda_view_approaches:
    thought_experiment_only:
      +enabled: false
